
INSERT INTO alunos (nome, serie, email, professor_id) VALUES
('Vânia Araújo','2A','vania.araujo1@aluno.educacao.sp.gov.br',1),
('Caio Cardoso','2D','caio.cardoso2@aluno.educacao.sp.gov.br',1),
('Guilherme Alves','1B','guilherme.alves3@aluno.educacao.sp.gov.br',1),
('Marcos Barbosa Faria','3E','marcos.barbosa.faria4@aluno.educacao.sp.gov.br',1),
('Igor Correia','1F','igor.correia5@aluno.educacao.sp.gov.br',1),
('Otávio Duarte','1C','otavio.duarte6@aluno.educacao.sp.gov.br',1),
('Fernando Ribeiro','2C','fernando.ribeiro7@aluno.educacao.sp.gov.br',1),
('Emanuel Viana','3F','emanuel.viana8@aluno.educacao.sp.gov.br',1),
('Nicolas Moura','3D','nicolas.moura9@aluno.educacao.sp.gov.br',1),
('Bruno Lima','1B','bruno.lima10@aluno.educacao.sp.gov.br',1),
('Lucas Santos','2F','lucas.santos11@aluno.educacao.sp.gov.br',1),
('Ivo Rocha','3C','ivo.rocha12@aluno.educacao.sp.gov.br',1),
('Felipe Viana','3G','felipe.viana13@aluno.educacao.sp.gov.br',1),
('Bruna Pinto','2C','bruna.pinto14@aluno.educacao.sp.gov.br',1),
('Gabriel Alves','1F','gabriel.alves15@aluno.educacao.sp.gov.br',1),
('Ivo Moura','1B','ivo.moura16@aluno.educacao.sp.gov.br',1),
('Nicole Ribeiro','2E','nicole.ribeiro17@aluno.educacao.sp.gov.br',1),
('Sofia Ribeiro','3B','sofia.ribeiro18@aluno.educacao.sp.gov.br',1),
('Felipe Ferreira','1C','felipe.ferreira19@aluno.educacao.sp.gov.br',1),
('Nicolas Oliveira','1F','nicolas.oliveira20@aluno.educacao.sp.gov.br',1),
('Emanuel Mendes Melo','1A','emanuel.mendes.melo21@aluno.educacao.sp.gov.br',1),
('Renata Viana','1D','renata.viana22@aluno.educacao.sp.gov.br',1),
('Lucas Alves Lopes','2D','lucas.alves.lopes23@aluno.educacao.sp.gov.br',1),
('Daniela Nunes','2B','daniela.nunes24@aluno.educacao.sp.gov.br',1),
('Vitor Nogueira','1A','vitor.nogueira25@aluno.educacao.sp.gov.br',1),
('Rafael Mota','1C','rafael.mota26@aluno.educacao.sp.gov.br',1),
('Samuel Rocha','3E','samuel.rocha27@aluno.educacao.sp.gov.br',1),
('Luan Araújo','3E','luan.araujo28@aluno.educacao.sp.gov.br',1),
('Larissa Duarte','2A','larissa.duarte29@aluno.educacao.sp.gov.br',1),
('Daniela Oliveira Correia','3F','daniela.oliveira.correia30@aluno.educacao.sp.gov.br',1),
('Cecília Braga Mota','1E','cecilia.braga.mota31@aluno.educacao.sp.gov.br',1),
('Gustavo Gomes','2C','gustavo.gomes32@aluno.educacao.sp.gov.br',1),
('Fabiana Mota','3D','fabiana.mota33@aluno.educacao.sp.gov.br',1),
('Ivo Araújo','3D','ivo.araujo34@aluno.educacao.sp.gov.br',1),
('Eduardo Freitas','1E','eduardo.freitas35@aluno.educacao.sp.gov.br',1),
('Emanuel Araújo','1E','emanuel.araujo36@aluno.educacao.sp.gov.br',1),
('Luan Souza','1B','luan.souza37@aluno.educacao.sp.gov.br',1),
('Vânia Ribeiro','3D','vania.ribeiro38@aluno.educacao.sp.gov.br',1),
('Rafael Mota','3E','rafael.mota39@aluno.educacao.sp.gov.br',1),
('Cecília Teixeira','2E','cecilia.teixeira40@aluno.educacao.sp.gov.br',1),
('Cecília Pereira','1G','cecilia.pereira41@aluno.educacao.sp.gov.br',1),
('Olívia Melo','1C','olivia.melo42@aluno.educacao.sp.gov.br',1),
('Daniela Azevedo','2C','daniela.azevedo43@aluno.educacao.sp.gov.br',1),
('Lívia Martins Barbosa','3E','livia.martins.barbosa44@aluno.educacao.sp.gov.br',1),
('Larissa Campos','3C','larissa.campos45@aluno.educacao.sp.gov.br',1),
('Eduardo Souza','3F','eduardo.souza46@aluno.educacao.sp.gov.br',1),
('Clara Rocha','2B','clara.rocha47@aluno.educacao.sp.gov.br',1),
('Clara Moura','3C','clara.moura48@aluno.educacao.sp.gov.br',1),
('Lorena Barbosa','3E','lorena.barbosa49@aluno.educacao.sp.gov.br',1),
('Laura Moura','3B','laura.moura50@aluno.educacao.sp.gov.br',1),
('Mariana Ferreira','2B','mariana.ferreira51@aluno.educacao.sp.gov.br',1),
('Nicolas Moura','1E','nicolas.moura52@aluno.educacao.sp.gov.br',1),
('Samuel Oliveira','3F','samuel.oliveira53@aluno.educacao.sp.gov.br',1),
('Júlia Melo','2A','julia.melo54@aluno.educacao.sp.gov.br',1),
('Vitor Ferreira','1F','vitor.ferreira55@aluno.educacao.sp.gov.br',1),
('Vitória Braga','3D','vitoria.braga56@aluno.educacao.sp.gov.br',1),
('Bruna Souza Ferreira','3A','bruna.souza.ferreira57@aluno.educacao.sp.gov.br',1),
('Júlia Almeida','1B','julia.almeida58@aluno.educacao.sp.gov.br',1),
('Paulo Santana','3B','paulo.santana59@aluno.educacao.sp.gov.br',1),
('Murilo Moura','3A','murilo.moura60@aluno.educacao.sp.gov.br',1),
('Caio Freitas','1F','caio.freitas61@aluno.educacao.sp.gov.br',1),
('Bruno Pinto','3F','bruno.pinto62@aluno.educacao.sp.gov.br',1),
('Alexandre Moura','2D','alexandre.moura63@aluno.educacao.sp.gov.br',1),
('Felipe Lopes','2D','felipe.lopes64@aluno.educacao.sp.gov.br',1),
('Guilherme Santos','3B','guilherme.santos65@aluno.educacao.sp.gov.br',1),
('Paulo Ferreira','2C','paulo.ferreira66@aluno.educacao.sp.gov.br',1),
('Amanda Mendes Gomes','3D','amanda.mendes.gomes67@aluno.educacao.sp.gov.br',1),
('Ivo Ribeiro','3C','ivo.ribeiro68@aluno.educacao.sp.gov.br',1),
('Beatriz Martins','2C','beatriz.martins69@aluno.educacao.sp.gov.br',1),
('Beatriz Nunes Castro','1B','beatriz.nunes.castro70@aluno.educacao.sp.gov.br',1),
('Ana Pereira','2E','ana.pereira71@aluno.educacao.sp.gov.br',1),
('Lucas Mendes Viana','1B','lucas.mendes.viana72@aluno.educacao.sp.gov.br',1),
('Vitória Silva','3A','vitoria.silva73@aluno.educacao.sp.gov.br',1),
('Nina Almeida','3F','nina.almeida74@aluno.educacao.sp.gov.br',1),
('João Carvalho Campos','1A','joao.carvalho.campos75@aluno.educacao.sp.gov.br',1),
('Luan Mota','2B','luan.mota76@aluno.educacao.sp.gov.br',1),
('Bruno Faria','1D','bruno.faria77@aluno.educacao.sp.gov.br',1),
('Daniela Mendes','1F','daniela.mendes78@aluno.educacao.sp.gov.br',1),
('Matheus Teixeira','3E','matheus.teixeira79@aluno.educacao.sp.gov.br',1),
('Bianca Teixeira','3A','bianca.teixeira80@aluno.educacao.sp.gov.br',1),
('Thiago Nogueira Freitas','1D','thiago.nogueira.freitas81@aluno.educacao.sp.gov.br',1),
('Bruno Mendes','3A','bruno.mendes82@aluno.educacao.sp.gov.br',1),
('Carolina Almeida','3C','carolina.almeida83@aluno.educacao.sp.gov.br',1),
('Fabiana Oliveira','3F','fabiana.oliveira84@aluno.educacao.sp.gov.br',1),
('Sofia Branco','1E','sofia.branco85@aluno.educacao.sp.gov.br',1),
('Matheus Souza','3A','matheus.souza86@aluno.educacao.sp.gov.br',1),
('Guilherme Melo Barbosa','1A','guilherme.melo.barbosa87@aluno.educacao.sp.gov.br',1),
('Lívia Faria Cardoso','2A','livia.faria.cardoso88@aluno.educacao.sp.gov.br',1),
('Sérgio Lopes','1G','sergio.lopes89@aluno.educacao.sp.gov.br',1),
('Pedro Pereira','1G','pedro.pereira90@aluno.educacao.sp.gov.br',1),
('Pedro Azevedo','1D','pedro.azevedo91@aluno.educacao.sp.gov.br',1),
('Bruno Martins Campos','3G','bruno.martins.campos92@aluno.educacao.sp.gov.br',1),
('Amanda Braga Almeida','2B','amanda.braga.almeida93@aluno.educacao.sp.gov.br',1),
('Felipe Pereira','2E','felipe.pereira94@aluno.educacao.sp.gov.br',1),
('Vitor Barbosa','1C','vitor.barbosa95@aluno.educacao.sp.gov.br',1),
('Igor Lima','3C','igor.lima96@aluno.educacao.sp.gov.br',1),
('Vitor Duarte','3F','vitor.duarte97@aluno.educacao.sp.gov.br',1),
('Eduardo Silva Lima','1B','eduardo.silva.lima98@aluno.educacao.sp.gov.br',1),
('Thiago Mota Castro','1B','thiago.mota.castro99@aluno.educacao.sp.gov.br',1),
('Beatriz Ribeiro','1E','beatriz.ribeiro100@aluno.educacao.sp.gov.br',1),
('Eduardo Mota Araújo','3F','eduardo.mota.araujo101@aluno.educacao.sp.gov.br',1),
('Sofia Melo','2D','sofia.melo102@aluno.educacao.sp.gov.br',1),
('Emanuel Freitas','1F','emanuel.freitas103@aluno.educacao.sp.gov.br',1),
('Luan Rocha','3G','luan.rocha104@aluno.educacao.sp.gov.br',1),
('Amanda Lima','3B','amanda.lima105@aluno.educacao.sp.gov.br',1),
('Ana Oliveira Pires','3D','ana.oliveira.pires106@aluno.educacao.sp.gov.br',1),
('Maria Nogueira Barbosa','1F','maria.nogueira.barbosa107@aluno.educacao.sp.gov.br',1),
('Nicole Castro','1G','nicole.castro108@aluno.educacao.sp.gov.br',1),
('Laura Ribeiro','3D','laura.ribeiro109@aluno.educacao.sp.gov.br',1),
('Bianca Correia','2A','bianca.correia110@aluno.educacao.sp.gov.br',1),
('Rafael Nogueira','2G','rafael.nogueira111@aluno.educacao.sp.gov.br',1),
('Fernando Oliveira','1F','fernando.oliveira112@aluno.educacao.sp.gov.br',1),
('Fabiana Moura','2C','fabiana.moura113@aluno.educacao.sp.gov.br',1),
('Paulo Oliveira Faria','1G','paulo.oliveira.faria114@aluno.educacao.sp.gov.br',1),
('Marcos Cardoso','1F','marcos.cardoso115@aluno.educacao.sp.gov.br',1),
('Marcos Gomes Faria','3D','marcos.gomes.faria116@aluno.educacao.sp.gov.br',1),
('Nicole Rocha','3C','nicole.rocha117@aluno.educacao.sp.gov.br',1),
('Sofia Almeida','3A','sofia.almeida118@aluno.educacao.sp.gov.br',1),
('Nina Freitas Melo','2G','nina.freitas.melo119@aluno.educacao.sp.gov.br',1),
('Igor Martins','1B','igor.martins120@aluno.educacao.sp.gov.br',1),
('Maria Fernandes','3E','maria.fernandes121@aluno.educacao.sp.gov.br',1),
('João Fernandes','3A','joao.fernandes122@aluno.educacao.sp.gov.br',1),
('Clara Lima','1F','clara.lima123@aluno.educacao.sp.gov.br',1),
('Carolina Melo','3C','carolina.melo124@aluno.educacao.sp.gov.br',1),
('Maria Azevedo','1D','maria.azevedo125@aluno.educacao.sp.gov.br',1),
('Olívia Pinto Lopes','1E','olivia.pinto.lopes126@aluno.educacao.sp.gov.br',1),
('Cecília Faria','2A','cecilia.faria127@aluno.educacao.sp.gov.br',1),
('Ruan Melo','1A','ruan.melo128@aluno.educacao.sp.gov.br',1),
('Maria Lopes','3B','maria.lopes129@aluno.educacao.sp.gov.br',1),
('Diego Silva','1E','diego.silva130@aluno.educacao.sp.gov.br',1),
('Samuel Lima Teixeira','3D','samuel.lima.teixeira131@aluno.educacao.sp.gov.br',1),
('Nicole Santos','1G','nicole.santos132@aluno.educacao.sp.gov.br',1),
('Nicolas Carvalho','1G','nicolas.carvalho133@aluno.educacao.sp.gov.br',1),
('André Pinto','1C','andre.pinto134@aluno.educacao.sp.gov.br',1),
('Fernando Braga','3A','fernando.braga135@aluno.educacao.sp.gov.br',1),
('Júlia Pinto','1G','julia.pinto136@aluno.educacao.sp.gov.br',1),
('Vitória Souza','1D','vitoria.souza137@aluno.educacao.sp.gov.br',1),
('Felipe Moura','1G','felipe.moura138@aluno.educacao.sp.gov.br',1),
('Otávio Duarte Cardoso','3B','otavio.duarte.cardoso139@aluno.educacao.sp.gov.br',1),
('Eduardo Almeida','3A','eduardo.almeida140@aluno.educacao.sp.gov.br',1),
('Murilo Gomes','2D','murilo.gomes141@aluno.educacao.sp.gov.br',1),
('Matheus Duarte','2B','matheus.duarte142@aluno.educacao.sp.gov.br',1),
('Sofia Almeida','3B','sofia.almeida143@aluno.educacao.sp.gov.br',1),
('Isabela Moreira','3E','isabela.moreira144@aluno.educacao.sp.gov.br',1),
('Matheus Santos','1B','matheus.santos145@aluno.educacao.sp.gov.br',1),
('Emanuel Braga Silva','2F','emanuel.braga.silva146@aluno.educacao.sp.gov.br',1),
('Mariana Nogueira','3F','mariana.nogueira147@aluno.educacao.sp.gov.br',1),
('Patrícia Viana','1D','patricia.viana148@aluno.educacao.sp.gov.br',1),
('Paulo Mendes','3D','paulo.mendes149@aluno.educacao.sp.gov.br',1),
('Ana Oliveira','1B','ana.oliveira150@aluno.educacao.sp.gov.br',1),
('Ivo Santos','2D','ivo.santos151@aluno.educacao.sp.gov.br',1),
('Sofia Pinto','1B','sofia.pinto152@aluno.educacao.sp.gov.br',1),
('Renata Lima','1C','renata.lima153@aluno.educacao.sp.gov.br',1),
('Júlia Alves','3A','julia.alves154@aluno.educacao.sp.gov.br',1),
('Clara Araújo','2E','clara.araujo155@aluno.educacao.sp.gov.br',1),
('Amanda Castro','3F','amanda.castro156@aluno.educacao.sp.gov.br',1),
('Matheus Azevedo','1C','matheus.azevedo157@aluno.educacao.sp.gov.br',1),
('Vânia Campos','2C','vania.campos158@aluno.educacao.sp.gov.br',1),
('Nicole Ribeiro Lopes','3E','nicole.ribeiro.lopes159@aluno.educacao.sp.gov.br',1),
('Clara Gomes','3G','clara.gomes160@aluno.educacao.sp.gov.br',1),
('Ana Campos','3E','ana.campos161@aluno.educacao.sp.gov.br',1),
('Murilo Moreira','1G','murilo.moreira162@aluno.educacao.sp.gov.br',1),
('Bianca Barbosa','3G','bianca.barbosa163@aluno.educacao.sp.gov.br',1),
('Sofia Costa','1A','sofia.costa164@aluno.educacao.sp.gov.br',1),
('Carolina Barbosa Ribeiro','2E','carolina.barbosa.ribeiro165@aluno.educacao.sp.gov.br',1),
('Larissa Gomes','2F','larissa.gomes166@aluno.educacao.sp.gov.br',1),
('Nicole Cardoso','1D','nicole.cardoso167@aluno.educacao.sp.gov.br',1),
('Larissa Melo','3D','larissa.melo168@aluno.educacao.sp.gov.br',1),
('Larissa Costa','2F','larissa.costa169@aluno.educacao.sp.gov.br',1),
('Ana Martins','3G','ana.martins170@aluno.educacao.sp.gov.br',1),
('Diego Rocha','2D','diego.rocha171@aluno.educacao.sp.gov.br',1),
('Henrique Pereira','1B','henrique.pereira172@aluno.educacao.sp.gov.br',1),
('Renata Fernandes','3E','renata.fernandes173@aluno.educacao.sp.gov.br',1),
('Vitor Braga','1E','vitor.braga174@aluno.educacao.sp.gov.br',1),
('Olívia Fernandes','2B','olivia.fernandes175@aluno.educacao.sp.gov.br',1),
('Sofia Campos','1E','sofia.campos176@aluno.educacao.sp.gov.br',1),
('Fernando Moura','1D','fernando.moura177@aluno.educacao.sp.gov.br',1),
('Ivo Santos','1C','ivo.santos178@aluno.educacao.sp.gov.br',1),
('Júlia Carvalho','1D','julia.carvalho179@aluno.educacao.sp.gov.br',1),
('Mariana Viana','1B','mariana.viana180@aluno.educacao.sp.gov.br',1),
('Fernando Almeida','1F','fernando.almeida181@aluno.educacao.sp.gov.br',1),
('Amanda Lima','2E','amanda.lima182@aluno.educacao.sp.gov.br',1),
('Carolina Melo','3F','carolina.melo183@aluno.educacao.sp.gov.br',1),
('Olívia Duarte','2C','olivia.duarte184@aluno.educacao.sp.gov.br',1),
('Marcos Carvalho Melo','3A','marcos.carvalho.melo185@aluno.educacao.sp.gov.br',1),
('Otávio Nunes','2F','otavio.nunes186@aluno.educacao.sp.gov.br',1),
('Murilo Moura','1B','murilo.moura187@aluno.educacao.sp.gov.br',1),
('Emanuel Teixeira','1C','emanuel.teixeira188@aluno.educacao.sp.gov.br',1),
('Emanuel Pinto','3C','emanuel.pinto189@aluno.educacao.sp.gov.br',1),
('Thiago Fernandes Ferreira','3C','thiago.fernandes.ferreira190@aluno.educacao.sp.gov.br',1),
('Thiago Nunes','1E','thiago.nunes191@aluno.educacao.sp.gov.br',1),
('Fernando Fernandes','2E','fernando.fernandes192@aluno.educacao.sp.gov.br',1),
('Eduardo Araújo','1E','eduardo.araujo193@aluno.educacao.sp.gov.br',1),
('Sérgio Pinto','1A','sergio.pinto194@aluno.educacao.sp.gov.br',1),
('Patrícia Souza','3E','patricia.souza195@aluno.educacao.sp.gov.br',1),
('Gustavo Barbosa','2C','gustavo.barbosa196@aluno.educacao.sp.gov.br',1),
('Larissa Santos','2G','larissa.santos197@aluno.educacao.sp.gov.br',1),
('Felipe Alves','2E','felipe.alves198@aluno.educacao.sp.gov.br',1),
('Felipe Santana','2A','felipe.santana199@aluno.educacao.sp.gov.br',1),
('Helena Campos','2E','helena.campos200@aluno.educacao.sp.gov.br',1);

INSERT INTO alunos (nome, serie, email, professor_id) VALUES
('Thiago Castro','3F','thiago.castro201@aluno.educacao.sp.gov.br',1),
('Alexandre Castro','2A','alexandre.castro202@aluno.educacao.sp.gov.br',1),
('Thiago Viana','1B','thiago.viana203@aluno.educacao.sp.gov.br',1),
('Vitor Santos Mota','1D','vitor.santos.mota204@aluno.educacao.sp.gov.br',1),
('Nicole Moura','2B','nicole.moura205@aluno.educacao.sp.gov.br',1),
('Ana Teixeira','1D','ana.teixeira206@aluno.educacao.sp.gov.br',1),
('Caio Freitas','3B','caio.freitas207@aluno.educacao.sp.gov.br',1),
('Ricardo Rocha','1C','ricardo.rocha208@aluno.educacao.sp.gov.br',1),
('Paulo Martins','3C','paulo.martins209@aluno.educacao.sp.gov.br',1),
('Patrícia Rocha','3B','patricia.rocha210@aluno.educacao.sp.gov.br',1),
('Emanuel Almeida','2B','emanuel.almeida211@aluno.educacao.sp.gov.br',1),
('Nina Martins','1E','nina.martins212@aluno.educacao.sp.gov.br',1),
('Vitória Ribeiro','1D','vitoria.ribeiro213@aluno.educacao.sp.gov.br',1),
('Bruno Mota','3B','bruno.mota214@aluno.educacao.sp.gov.br',1),
('Lívia Santana','1F','livia.santana215@aluno.educacao.sp.gov.br',1),
('Diego Castro Santana','2A','diego.castro.santana216@aluno.educacao.sp.gov.br',1),
('Cecília Gomes Ferreira','2C','cecilia.gomes.ferreira217@aluno.educacao.sp.gov.br',1),
('Emanuel Lima Freitas','1F','emanuel.lima.freitas218@aluno.educacao.sp.gov.br',1),
('Beatriz Campos','1F','beatriz.campos219@aluno.educacao.sp.gov.br',1),
('Igor Cardoso','1B','igor.cardoso220@aluno.educacao.sp.gov.br',1),
('Lívia Cardoso','2A','livia.cardoso221@aluno.educacao.sp.gov.br',1),
('Nicole Lima','1G','nicole.lima222@aluno.educacao.sp.gov.br',1),
('Bianca Santana','2A','bianca.santana223@aluno.educacao.sp.gov.br',1),
('Luan Barbosa Ribeiro','1A','luan.barbosa.ribeiro224@aluno.educacao.sp.gov.br',1),
('Caio Santos Rocha','1B','caio.santos.rocha225@aluno.educacao.sp.gov.br',1),
('Vânia Faria Lima','2A','vania.faria.lima226@aluno.educacao.sp.gov.br',1),
('André Azevedo','2B','andre.azevedo227@aluno.educacao.sp.gov.br',1),
('Murilo Araújo','3C','murilo.araujo228@aluno.educacao.sp.gov.br',1),
('Camila Viana','2C','camila.viana229@aluno.educacao.sp.gov.br',1),
('Lucas Moreira','3E','lucas.moreira230@aluno.educacao.sp.gov.br',1),
('Vânia Oliveira','1F','vania.oliveira231@aluno.educacao.sp.gov.br',1),
('Cecília Carvalho','2E','cecilia.carvalho232@aluno.educacao.sp.gov.br',1),
('Marcos Martins','2A','marcos.martins233@aluno.educacao.sp.gov.br',1),
('Laura Araújo Moreira','3E','laura.araujo.moreira234@aluno.educacao.sp.gov.br',1),
('Thiago Azevedo Alves','3B','thiago.azevedo.alves235@aluno.educacao.sp.gov.br',1),
('Ruan Ribeiro','3B','ruan.ribeiro236@aluno.educacao.sp.gov.br',1),
('Bruna Fernandes','2G','bruna.fernandes237@aluno.educacao.sp.gov.br',1),
('Larissa Duarte Alves','1F','larissa.duarte.alves238@aluno.educacao.sp.gov.br',1),
('Camila Santana','1B','camila.santana239@aluno.educacao.sp.gov.br',1),
('Murilo Moura','1D','murilo.moura240@aluno.educacao.sp.gov.br',1),
('Lívia Moreira','3G','livia.moreira241@aluno.educacao.sp.gov.br',1),
('Sérgio Mendes','3B','sergio.mendes242@aluno.educacao.sp.gov.br',1),
('Camila Faria Pires','1G','camila.faria.pires243@aluno.educacao.sp.gov.br',1),
('Cecília Branco Moura','1F','cecilia.branco.moura244@aluno.educacao.sp.gov.br',1),
('Nina Ribeiro Fernandes','2B','nina.ribeiro.fernandes245@aluno.educacao.sp.gov.br',1),
('Caio Oliveira','2B','caio.oliveira246@aluno.educacao.sp.gov.br',1),
('Larissa Correia Teixeira','2A','larissa.correia.teixeira247@aluno.educacao.sp.gov.br',1),
('Vânia Fernandes','2F','vania.fernandes248@aluno.educacao.sp.gov.br',1),
('Marcos Braga','2D','marcos.braga249@aluno.educacao.sp.gov.br',1),
('Paulo Carvalho Ribeiro','3D','paulo.carvalho.ribeiro250@aluno.educacao.sp.gov.br',1),
('Júlia Ferreira','2C','julia.ferreira251@aluno.educacao.sp.gov.br',1),
('Clara Oliveira','2B','clara.oliveira252@aluno.educacao.sp.gov.br',1),
('Olívia Viana','2A','olivia.viana253@aluno.educacao.sp.gov.br',1),
('Henrique Pereira','2A','henrique.pereira254@aluno.educacao.sp.gov.br',1),
('Marcos Campos','3B','marcos.campos255@aluno.educacao.sp.gov.br',1),
('Marcos Carvalho','2E','marcos.carvalho256@aluno.educacao.sp.gov.br',1),
('Felipe Ferreira','2B','felipe.ferreira257@aluno.educacao.sp.gov.br',1),
('Carolina Pereira','1F','carolina.pereira258@aluno.educacao.sp.gov.br',1),
('Ricardo Gomes','3F','ricardo.gomes259@aluno.educacao.sp.gov.br',1),
('Paulo Azevedo Costa','3F','paulo.azevedo.costa260@aluno.educacao.sp.gov.br',1),
('João Freitas','3C','joao.freitas261@aluno.educacao.sp.gov.br',1),
('Cecília Castro Braga','2C','cecilia.castro.braga262@aluno.educacao.sp.gov.br',1),
('Carolina Silva','2E','carolina.silva263@aluno.educacao.sp.gov.br',1),
('Vitor Fernandes','3C','vitor.fernandes264@aluno.educacao.sp.gov.br',1),
('Lorena Souza','3E','lorena.souza265@aluno.educacao.sp.gov.br',1),
('Sérgio Nogueira','2D','sergio.nogueira266@aluno.educacao.sp.gov.br',1),
('Samuel Mendes','3B','samuel.mendes267@aluno.educacao.sp.gov.br',1),
('Luan Mendes Lima','1C','luan.mendes.lima268@aluno.educacao.sp.gov.br',1),
('Vitor Almeida','1F','vitor.almeida269@aluno.educacao.sp.gov.br',1),
('Alexandre Gomes','1C','alexandre.gomes270@aluno.educacao.sp.gov.br',1),
('Felipe Nunes','3F','felipe.nunes271@aluno.educacao.sp.gov.br',1),
('Olívia Moreira','2A','olivia.moreira272@aluno.educacao.sp.gov.br',1),
('Caio Nunes Almeida','2G','caio.nunes.almeida273@aluno.educacao.sp.gov.br',1),
('Vitória Rocha Fernandes','2E','vitoria.rocha.fernandes274@aluno.educacao.sp.gov.br',1),
('Vitor Moura','3D','vitor.moura275@aluno.educacao.sp.gov.br',1),
('Marcos Castro Araújo','1E','marcos.castro.araujo276@aluno.educacao.sp.gov.br',1),
('Sofia Ferreira','1B','sofia.ferreira277@aluno.educacao.sp.gov.br',1),
('Pedro Mendes','2C','pedro.mendes278@aluno.educacao.sp.gov.br',1),
('Vitória Santana Pereira','2D','vitoria.santana.pereira279@aluno.educacao.sp.gov.br',1),
('Ricardo Lopes','3F','ricardo.lopes280@aluno.educacao.sp.gov.br',1),
('Felipe Santos','1D','felipe.santos281@aluno.educacao.sp.gov.br',1),
('Ivo Campos','2B','ivo.campos282@aluno.educacao.sp.gov.br',1),
('Maria Castro','2E','maria.castro283@aluno.educacao.sp.gov.br',1),
('Fabiana Campos','3F','fabiana.campos284@aluno.educacao.sp.gov.br',1),
('Henrique Mendes Pires','1E','henrique.mendes.pires285@aluno.educacao.sp.gov.br',1),
('Patrícia Freitas','1C','patricia.freitas286@aluno.educacao.sp.gov.br',1),
('Amanda Martins Ferreira','3E','amanda.martins.ferreira287@aluno.educacao.sp.gov.br',1),
('Ruan Pinto','2C','ruan.pinto288@aluno.educacao.sp.gov.br',1),
('Henrique Souza','2B','henrique.souza289@aluno.educacao.sp.gov.br',1),
('Paulo Pereira','1F','paulo.pereira290@aluno.educacao.sp.gov.br',1),
('Mariana Ribeiro Martins','2D','mariana.ribeiro.martins291@aluno.educacao.sp.gov.br',1),
('Guilherme Pereira Souza','2G','guilherme.pereira.souza292@aluno.educacao.sp.gov.br',1),
('Paulo Moreira','3D','paulo.moreira293@aluno.educacao.sp.gov.br',1),
('Ruan Santana','3A','ruan.santana294@aluno.educacao.sp.gov.br',1),
('Helena Ferreira Lima','3B','helena.ferreira.lima295@aluno.educacao.sp.gov.br',1),
('Diego Souza','2E','diego.souza296@aluno.educacao.sp.gov.br',1),
('Nina Moura','3A','nina.moura297@aluno.educacao.sp.gov.br',1),
('Nina Braga','3B','nina.braga298@aluno.educacao.sp.gov.br',1),
('Lucas Gomes','1E','lucas.gomes299@aluno.educacao.sp.gov.br',1),
('Laura Castro Costa','2F','laura.castro.costa300@aluno.educacao.sp.gov.br',1),
('Sofia Azevedo','2C','sofia.azevedo301@aluno.educacao.sp.gov.br',1),
('Caio Lima','2D','caio.lima302@aluno.educacao.sp.gov.br',1),
('Sofia Alves','1A','sofia.alves303@aluno.educacao.sp.gov.br',1),
('Lucas Alves','2G','lucas.alves304@aluno.educacao.sp.gov.br',1),
('Gustavo Fernandes','1A','gustavo.fernandes305@aluno.educacao.sp.gov.br',1),
('Laura Pinto','1B','laura.pinto306@aluno.educacao.sp.gov.br',1),
('Murilo Lima','2G','murilo.lima307@aluno.educacao.sp.gov.br',1),
('Sofia Souza','3F','sofia.souza308@aluno.educacao.sp.gov.br',1),
('Amanda Fernandes','2A','amanda.fernandes309@aluno.educacao.sp.gov.br',1),
('Lorena Melo','2F','lorena.melo310@aluno.educacao.sp.gov.br',1),
('Larissa Pereira Teixeira','2C','larissa.pereira.teixeira311@aluno.educacao.sp.gov.br',1),
('Maria Gomes','3E','maria.gomes312@aluno.educacao.sp.gov.br',1),
('Vitor Nunes','1A','vitor.nunes313@aluno.educacao.sp.gov.br',1),
('Rafael Correia','1A','rafael.correia314@aluno.educacao.sp.gov.br',1),
('Igor Ferreira','3A','igor.ferreira315@aluno.educacao.sp.gov.br',1),
('Marcos Duarte','2A','marcos.duarte316@aluno.educacao.sp.gov.br',1),
('Caio Nunes Mota','2F','caio.nunes.mota317@aluno.educacao.sp.gov.br',1),
('João Santos','3B','joao.santos318@aluno.educacao.sp.gov.br',1),
('Bianca Araújo','2E','bianca.araujo319@aluno.educacao.sp.gov.br',1),
('Caio Rocha','1E','caio.rocha320@aluno.educacao.sp.gov.br',1),
('Bruna Carvalho','2G','bruna.carvalho321@aluno.educacao.sp.gov.br',1),
('Ruan Carvalho Branco','3C','ruan.carvalho.branco322@aluno.educacao.sp.gov.br',1),
('Fabiana Freitas','2F','fabiana.freitas323@aluno.educacao.sp.gov.br',1),
('Sofia Santana','2G','sofia.santana324@aluno.educacao.sp.gov.br',1),
('Henrique Duarte','3G','henrique.duarte325@aluno.educacao.sp.gov.br',1),
('Amanda Castro','3E','amanda.castro326@aluno.educacao.sp.gov.br',1),
('Bruno Freitas Alves','2E','bruno.freitas.alves327@aluno.educacao.sp.gov.br',1),
('Cecília Carvalho','3A','cecilia.carvalho328@aluno.educacao.sp.gov.br',1),
('Nicole Santos','1C','nicole.santos329@aluno.educacao.sp.gov.br',1),
('Rafael Ferreira','2F','rafael.ferreira330@aluno.educacao.sp.gov.br',1),
('Bruna Moreira','2A','bruna.moreira331@aluno.educacao.sp.gov.br',1),
('Gustavo Moreira','2C','gustavo.moreira332@aluno.educacao.sp.gov.br',1),
('Caio Ribeiro','2B','caio.ribeiro333@aluno.educacao.sp.gov.br',1),
('Nicole Santana','2B','nicole.santana334@aluno.educacao.sp.gov.br',1),
('Otávio Martins','2C','otavio.martins335@aluno.educacao.sp.gov.br',1),
('Bruno Correia','1G','bruno.correia336@aluno.educacao.sp.gov.br',1),
('Henrique Ribeiro Alves','2F','henrique.ribeiro.alves337@aluno.educacao.sp.gov.br',1),
('Luan Faria','2B','luan.faria338@aluno.educacao.sp.gov.br',1),
('Daniela Pires','1D','daniela.pires339@aluno.educacao.sp.gov.br',1),
('Maria Freitas Correia','2F','maria.freitas.correia340@aluno.educacao.sp.gov.br',1),
('Sérgio Braga','3C','sergio.braga341@aluno.educacao.sp.gov.br',1),
('Diego Lima Correia','2B','diego.lima.correia342@aluno.educacao.sp.gov.br',1),
('Igor Lima','3B','igor.lima343@aluno.educacao.sp.gov.br',1),
('Guilherme Alves','1F','guilherme.alves344@aluno.educacao.sp.gov.br',1),
('Ana Cardoso','3D','ana.cardoso345@aluno.educacao.sp.gov.br',1),
('Ruan Castro','2B','ruan.castro346@aluno.educacao.sp.gov.br',1),
('Henrique Barbosa','3D','henrique.barbosa347@aluno.educacao.sp.gov.br',1),
('Guilherme Faria','3C','guilherme.faria348@aluno.educacao.sp.gov.br',1),
('Eduardo Pires','2C','eduardo.pires349@aluno.educacao.sp.gov.br',1),
('Clara Pereira','3E','clara.pereira350@aluno.educacao.sp.gov.br',1),
('Diego Santana','2B','diego.santana351@aluno.educacao.sp.gov.br',1),
('Ivo Nogueira','2G','ivo.nogueira352@aluno.educacao.sp.gov.br',1),
('Ivo Pinto Martins','1B','ivo.pinto.martins353@aluno.educacao.sp.gov.br',1),
('Ivo Freitas','3C','ivo.freitas354@aluno.educacao.sp.gov.br',1),
('Carolina Moreira','2B','carolina.moreira355@aluno.educacao.sp.gov.br',1),
('Felipe Mota Braga','1E','felipe.mota.braga356@aluno.educacao.sp.gov.br',1),
('Júlia Faria','1D','julia.faria357@aluno.educacao.sp.gov.br',1),
('Renata Lima','1B','renata.lima358@aluno.educacao.sp.gov.br',1),
('Camila Fernandes','1B','camila.fernandes359@aluno.educacao.sp.gov.br',1),
('Maria Oliveira','1D','maria.oliveira360@aluno.educacao.sp.gov.br',1),
('Thiago Braga Duarte','2E','thiago.braga.duarte361@aluno.educacao.sp.gov.br',1),
('Luan Correia','3E','luan.correia362@aluno.educacao.sp.gov.br',1),
('Ivo Almeida','3E','ivo.almeida363@aluno.educacao.sp.gov.br',1),
('Sofia Souza','3B','sofia.souza364@aluno.educacao.sp.gov.br',1),
('Emanuel Viana Lopes','2F','emanuel.viana.lopes365@aluno.educacao.sp.gov.br',1),
('Laura Costa','3G','laura.costa366@aluno.educacao.sp.gov.br',1),
('Marcos Correia Martins','2E','marcos.correia.martins367@aluno.educacao.sp.gov.br',1),
('Ruan Braga','1B','ruan.braga368@aluno.educacao.sp.gov.br',1),
('Fernando Fernandes','3F','fernando.fernandes369@aluno.educacao.sp.gov.br',1),
('Caio Alves','3B','caio.alves370@aluno.educacao.sp.gov.br',1),
('Fabiana Araújo','1B','fabiana.araujo371@aluno.educacao.sp.gov.br',1),
('Gustavo Faria','1E','gustavo.faria372@aluno.educacao.sp.gov.br',1),
('João Rocha Viana','3E','joao.rocha.viana373@aluno.educacao.sp.gov.br',1),
('Samuel Barbosa','1F','samuel.barbosa374@aluno.educacao.sp.gov.br',1),
('Bruno Lopes Pinto','3F','bruno.lopes.pinto375@aluno.educacao.sp.gov.br',1),
('Helena Santana','3A','helena.santana376@aluno.educacao.sp.gov.br',1),
('Vânia Nogueira','2D','vania.nogueira377@aluno.educacao.sp.gov.br',1),
('Eduardo Lima','1F','eduardo.lima378@aluno.educacao.sp.gov.br',1),
('Matheus Ribeiro','2A','matheus.ribeiro379@aluno.educacao.sp.gov.br',1),
('Marcos Pires','2A','marcos.pires380@aluno.educacao.sp.gov.br',1),
('Fabiana Pinto','1C','fabiana.pinto381@aluno.educacao.sp.gov.br',1),
('Fernando Pires','3B','fernando.pires382@aluno.educacao.sp.gov.br',1),
('Murilo Castro','1A','murilo.castro383@aluno.educacao.sp.gov.br',1),
('Pedro Oliveira','3F','pedro.oliveira384@aluno.educacao.sp.gov.br',1),
('Lucas Branco Freitas','3C','lucas.branco.freitas385@aluno.educacao.sp.gov.br',1),
('Nicole Costa','2F','nicole.costa386@aluno.educacao.sp.gov.br',1),
('Murilo Pinto','2F','murilo.pinto387@aluno.educacao.sp.gov.br',1),
('Maria Lima','3E','maria.lima388@aluno.educacao.sp.gov.br',1),
('Eduardo Nogueira','1D','eduardo.nogueira389@aluno.educacao.sp.gov.br',1),
('Samuel Souza','1F','samuel.souza390@aluno.educacao.sp.gov.br',1),
('Vânia Alves','2A','vania.alves391@aluno.educacao.sp.gov.br',1),
('Henrique Lima','1A','henrique.lima392@aluno.educacao.sp.gov.br',1),
('Matheus Lima','2G','matheus.lima393@aluno.educacao.sp.gov.br',1),
('Igor Campos Azevedo','1D','igor.campos.azevedo394@aluno.educacao.sp.gov.br',1),
('Nina Santana','3F','nina.santana395@aluno.educacao.sp.gov.br',1),
('Ana Barbosa','2G','ana.barbosa396@aluno.educacao.sp.gov.br',1),
('Cecília Pires','3F','cecilia.pires397@aluno.educacao.sp.gov.br',1),
('Matheus Freitas','2A','matheus.freitas398@aluno.educacao.sp.gov.br',1),
('Laura Santos','2C','laura.santos399@aluno.educacao.sp.gov.br',1),
('Olívia Gomes','3F','olivia.gomes400@aluno.educacao.sp.gov.br',1);

INSERT INTO alunos (nome, serie, email, professor_id) VALUES
('Júlia Fernandes','1G','julia.fernandes401@aluno.educacao.sp.gov.br',1),
('Eduardo Freitas','1A','eduardo.freitas402@aluno.educacao.sp.gov.br',1),
('Lívia Rocha','2A','livia.rocha403@aluno.educacao.sp.gov.br',1),
('Murilo Teixeira','3A','murilo.teixeira404@aluno.educacao.sp.gov.br',1),
('Diego Mota','1F','diego.mota405@aluno.educacao.sp.gov.br',1),
('Nicole Nogueira Carvalho','2E','nicole.nogueira.carvalho406@aluno.educacao.sp.gov.br',1),
('Bianca Branco','1F','bianca.branco407@aluno.educacao.sp.gov.br',1),
('Nicolas Duarte','2A','nicolas.duarte408@aluno.educacao.sp.gov.br',1),
('Bianca Araújo','1B','bianca.araujo409@aluno.educacao.sp.gov.br',1),
('Henrique Pires','3F','henrique.pires410@aluno.educacao.sp.gov.br',1),
('Amanda Silva','1E','amanda.silva411@aluno.educacao.sp.gov.br',1),
('Helena Ferreira','1F','helena.ferreira412@aluno.educacao.sp.gov.br',1),
('Alexandre Viana','1F','alexandre.viana413@aluno.educacao.sp.gov.br',1),
('Henrique Barbosa','3G','henrique.barbosa414@aluno.educacao.sp.gov.br',1),
('João Costa','3E','joao.costa415@aluno.educacao.sp.gov.br',1),
('Ricardo Araújo','2F','ricardo.araujo416@aluno.educacao.sp.gov.br',1),
('Amanda Azevedo Alves','3B','amanda.azevedo.alves417@aluno.educacao.sp.gov.br',1),
('João Almeida','2E','joao.almeida418@aluno.educacao.sp.gov.br',1),
('Emanuel Moura','2A','emanuel.moura419@aluno.educacao.sp.gov.br',1),
('Vitória Pires Rocha','3B','vitoria.pires.rocha420@aluno.educacao.sp.gov.br',1),
('Beatriz Pereira','2F','beatriz.pereira421@aluno.educacao.sp.gov.br',1),
('Lucas Carvalho Barbosa','3F','lucas.carvalho.barbosa422@aluno.educacao.sp.gov.br',1),
('Camila Pereira','3A','camila.pereira423@aluno.educacao.sp.gov.br',1),
('Mariana Martins','1G','mariana.martins424@aluno.educacao.sp.gov.br',1),
('Vânia Araújo','1G','vania.araujo425@aluno.educacao.sp.gov.br',1),
('Marcos Costa','2G','marcos.costa426@aluno.educacao.sp.gov.br',1),
('Diego Pereira Pires','2E','diego.pereira.pires427@aluno.educacao.sp.gov.br',1),
('Nicole Mendes Martins','3C','nicole.mendes.martins428@aluno.educacao.sp.gov.br',1),
('Carolina Viana Branco','3E','carolina.viana.branco429@aluno.educacao.sp.gov.br',1),
('Otávio Mota','1A','otavio.mota430@aluno.educacao.sp.gov.br',1),
('Cecília Souza','1A','cecilia.souza431@aluno.educacao.sp.gov.br',1),
('Guilherme Mota','3D','guilherme.mota432@aluno.educacao.sp.gov.br',1),
('Henrique Braga','2C','henrique.braga433@aluno.educacao.sp.gov.br',1),
('Isabela Ferreira','1G','isabela.ferreira434@aluno.educacao.sp.gov.br',1),
('Olívia Pereira','3G','olivia.pereira435@aluno.educacao.sp.gov.br',1),
('Eduardo Nogueira','1F','eduardo.nogueira436@aluno.educacao.sp.gov.br',1),
('Felipe Cardoso','2D','felipe.cardoso437@aluno.educacao.sp.gov.br',1),
('Ricardo Silva','1E','ricardo.silva438@aluno.educacao.sp.gov.br',1),
('Lucas Rocha','1E','lucas.rocha439@aluno.educacao.sp.gov.br',1),
('Samuel Mendes Melo','3D','samuel.mendes.melo440@aluno.educacao.sp.gov.br',1),
('Mariana Braga','1D','mariana.braga441@aluno.educacao.sp.gov.br',1),
('Amanda Pinto','1G','amanda.pinto442@aluno.educacao.sp.gov.br',1),
('Murilo Santana','2D','murilo.santana443@aluno.educacao.sp.gov.br',1),
('Gustavo Fernandes','1D','gustavo.fernandes444@aluno.educacao.sp.gov.br',1),
('Murilo Faria','3G','murilo.faria445@aluno.educacao.sp.gov.br',1),
('Mariana Almeida','3E','mariana.almeida446@aluno.educacao.sp.gov.br',1),
('Rafael Campos','1D','rafael.campos447@aluno.educacao.sp.gov.br',1),
('Ana Pires','3F','ana.pires448@aluno.educacao.sp.gov.br',1),
('Maria Viana','3F','maria.viana449@aluno.educacao.sp.gov.br',1),
('Bianca Carvalho','1A','bianca.carvalho450@aluno.educacao.sp.gov.br',1),
('Diego Azevedo','1A','diego.azevedo451@aluno.educacao.sp.gov.br',1),
('Vânia Ferreira','1G','vania.ferreira452@aluno.educacao.sp.gov.br',1),
('André Pires','2A','andre.pires453@aluno.educacao.sp.gov.br',1),
('Gabriel Mendes Martins','2A','gabriel.mendes.martins454@aluno.educacao.sp.gov.br',1),
('Amanda Rocha','1D','amanda.rocha455@aluno.educacao.sp.gov.br',1),
('Cecília Mota Nunes','1C','cecilia.mota.nunes456@aluno.educacao.sp.gov.br',1),
('Fernando Duarte Correia','1G','fernando.duarte.correia457@aluno.educacao.sp.gov.br',1),
('Maria Teixeira','1F','maria.teixeira458@aluno.educacao.sp.gov.br',1),
('Larissa Cardoso','1F','larissa.cardoso459@aluno.educacao.sp.gov.br',1),
('Lívia Azevedo','1C','livia.azevedo460@aluno.educacao.sp.gov.br',1),
('João Ferreira','2B','joao.ferreira461@aluno.educacao.sp.gov.br',1),
('Mariana Mendes Carvalho','1G','mariana.mendes.carvalho462@aluno.educacao.sp.gov.br',1),
('Bruna Fernandes','1F','bruna.fernandes463@aluno.educacao.sp.gov.br',1),
('Vitória Lima','3B','vitoria.lima464@aluno.educacao.sp.gov.br',1),
('Lucas Braga','1C','lucas.braga465@aluno.educacao.sp.gov.br',1),
('Sofia Melo Araújo','2F','sofia.melo.araujo466@aluno.educacao.sp.gov.br',1),
('Carolina Pinto','3D','carolina.pinto467@aluno.educacao.sp.gov.br',1),
('Thiago Alves','1B','thiago.alves468@aluno.educacao.sp.gov.br',1),
('Sofia Melo','2C','sofia.melo469@aluno.educacao.sp.gov.br',1),
('André Duarte','3B','andre.duarte470@aluno.educacao.sp.gov.br',1),
('Fabiana Almeida','3B','fabiana.almeida471@aluno.educacao.sp.gov.br',1),
('Emanuel Azevedo','3F','emanuel.azevedo472@aluno.educacao.sp.gov.br',1),
('Samuel Oliveira Mota','2A','samuel.oliveira.mota473@aluno.educacao.sp.gov.br',1),
('João Lopes','2F','joao.lopes474@aluno.educacao.sp.gov.br',1),
('Guilherme Moreira','3B','guilherme.moreira475@aluno.educacao.sp.gov.br',1),
('Olívia Moreira','3E','olivia.moreira476@aluno.educacao.sp.gov.br',1),
('Nicole Viana','1D','nicole.viana477@aluno.educacao.sp.gov.br',1),
('Vânia Mota Pereira','2F','vania.mota.pereira478@aluno.educacao.sp.gov.br',1),
('Nina Costa','1F','nina.costa479@aluno.educacao.sp.gov.br',1),
('Fernando Branco','3D','fernando.branco480@aluno.educacao.sp.gov.br',1),
('Laura Martins','2C','laura.martins481@aluno.educacao.sp.gov.br',1),
('Marcos Ferreira','3C','marcos.ferreira482@aluno.educacao.sp.gov.br',1),
('Samuel Gomes','2F','samuel.gomes483@aluno.educacao.sp.gov.br',1),
('Mariana Moura','1D','mariana.moura484@aluno.educacao.sp.gov.br',1),
('Caio Viana','2A','caio.viana485@aluno.educacao.sp.gov.br',1),
('Renata Moreira','1B','renata.moreira486@aluno.educacao.sp.gov.br',1),
('Marcos Pinto Oliveira','2B','marcos.pinto.oliveira487@aluno.educacao.sp.gov.br',1),
('Clara Rocha Gomes','1G','clara.rocha.gomes488@aluno.educacao.sp.gov.br',1),
('Thiago Barbosa','2A','thiago.barbosa489@aluno.educacao.sp.gov.br',1),
('Pedro Araújo','3E','pedro.araujo490@aluno.educacao.sp.gov.br',1),
('Alexandre Nogueira','1E','alexandre.nogueira491@aluno.educacao.sp.gov.br',1),
('Ricardo Pereira','3F','ricardo.pereira492@aluno.educacao.sp.gov.br',1),
('Camila Campos Souza','1E','camila.campos.souza493@aluno.educacao.sp.gov.br',1),
('Olívia Almeida','2B','olivia.almeida494@aluno.educacao.sp.gov.br',1),
('Otávio Branco Melo','3B','otavio.branco.melo495@aluno.educacao.sp.gov.br',1),
('Fabiana Cardoso','1C','fabiana.cardoso496@aluno.educacao.sp.gov.br',1),
('Nicolas Faria Souza','2E','nicolas.faria.souza497@aluno.educacao.sp.gov.br',1),
('Marcos Duarte','3A','marcos.duarte498@aluno.educacao.sp.gov.br',1),
('Beatriz Costa','1E','beatriz.costa499@aluno.educacao.sp.gov.br',1),
('Luan Lima Nunes','1G','luan.lima.nunes500@aluno.educacao.sp.gov.br',1),
('Sérgio Pinto Rocha','1E','sergio.pinto.rocha501@aluno.educacao.sp.gov.br',1),
('Fernando Pinto','3D','fernando.pinto502@aluno.educacao.sp.gov.br',1),
('Lorena Freitas','3D','lorena.freitas503@aluno.educacao.sp.gov.br',1),
('Fernando Almeida','2C','fernando.almeida504@aluno.educacao.sp.gov.br',1),
('Thiago Fernandes','1E','thiago.fernandes505@aluno.educacao.sp.gov.br',1),
('Gustavo Souza','1A','gustavo.souza506@aluno.educacao.sp.gov.br',1),
('Marcos Duarte','3B','marcos.duarte507@aluno.educacao.sp.gov.br',1),
('Isabela Nunes','1E','isabela.nunes508@aluno.educacao.sp.gov.br',1),
('Murilo Santana','3G','murilo.santana509@aluno.educacao.sp.gov.br',1),
('Henrique Viana','3E','henrique.viana510@aluno.educacao.sp.gov.br',1),
('Maria Duarte','1D','maria.duarte511@aluno.educacao.sp.gov.br',1),
('Igor Teixeira','2C','igor.teixeira512@aluno.educacao.sp.gov.br',1),
('Gustavo Nunes','3E','gustavo.nunes513@aluno.educacao.sp.gov.br',1),
('Diego Duarte','3A','diego.duarte514@aluno.educacao.sp.gov.br',1),
('Maria Moreira','1F','maria.moreira515@aluno.educacao.sp.gov.br',1),
('Larissa Lopes','1A','larissa.lopes516@aluno.educacao.sp.gov.br',1),
('Sérgio Viana','1E','sergio.viana517@aluno.educacao.sp.gov.br',1),
('Camila Moura','2F','camila.moura518@aluno.educacao.sp.gov.br',1),
('Gustavo Moura','1B','gustavo.moura519@aluno.educacao.sp.gov.br',1),
('Vitória Araújo','2F','vitoria.araujo520@aluno.educacao.sp.gov.br',1),
('Bruna Ferreira','3E','bruna.ferreira521@aluno.educacao.sp.gov.br',1),
('Bruno Campos','2B','bruno.campos522@aluno.educacao.sp.gov.br',1),
('Rafael Ribeiro','3F','rafael.ribeiro523@aluno.educacao.sp.gov.br',1),
('Carolina Moreira','1E','carolina.moreira524@aluno.educacao.sp.gov.br',1),
('Bruno Castro','1D','bruno.castro525@aluno.educacao.sp.gov.br',1),
('Bruno Silva','1E','bruno.silva526@aluno.educacao.sp.gov.br',1),
('Murilo Costa','2B','murilo.costa527@aluno.educacao.sp.gov.br',1),
('Camila Silva','3E','camila.silva528@aluno.educacao.sp.gov.br',1),
('Igor Faria','1D','igor.faria529@aluno.educacao.sp.gov.br',1),
('Carolina Araújo','3F','carolina.araujo530@aluno.educacao.sp.gov.br',1),
('Fabiana Santana','1A','fabiana.santana531@aluno.educacao.sp.gov.br',1),
('Nicole Santos','2E','nicole.santos532@aluno.educacao.sp.gov.br',1),
('Patrícia Ferreira','2B','patricia.ferreira533@aluno.educacao.sp.gov.br',1),
('Vitor Almeida','2G','vitor.almeida534@aluno.educacao.sp.gov.br',1),
('Isabela Pinto','2E','isabela.pinto535@aluno.educacao.sp.gov.br',1),
('Clara Azevedo','1D','clara.azevedo536@aluno.educacao.sp.gov.br',1),
('Vânia Teixeira','1D','vania.teixeira537@aluno.educacao.sp.gov.br',1),
('Nina Moreira','3A','nina.moreira538@aluno.educacao.sp.gov.br',1),
('Camila Araújo','2B','camila.araujo539@aluno.educacao.sp.gov.br',1),
('Maria Santos','1E','maria.santos540@aluno.educacao.sp.gov.br',1),
('Gustavo Castro Costa','1B','gustavo.castro.costa541@aluno.educacao.sp.gov.br',1),
('Igor Souza','3B','igor.souza542@aluno.educacao.sp.gov.br',1),
('Gabriel Ferreira','1F','gabriel.ferreira543@aluno.educacao.sp.gov.br',1),
('Sérgio Correia Braga','1B','sergio.correia.braga544@aluno.educacao.sp.gov.br',1),
('Amanda Costa','3B','amanda.costa545@aluno.educacao.sp.gov.br',1),
('Henrique Moura','3C','henrique.moura546@aluno.educacao.sp.gov.br',1),
('Júlia Correia','2E','julia.correia547@aluno.educacao.sp.gov.br',1),
('Carolina Correia','2D','carolina.correia548@aluno.educacao.sp.gov.br',1),
('Matheus Pereira','3E','matheus.pereira549@aluno.educacao.sp.gov.br',1),
('Amanda Ribeiro','3E','amanda.ribeiro550@aluno.educacao.sp.gov.br',1),
('Paulo Freitas Castro','1D','paulo.freitas.castro551@aluno.educacao.sp.gov.br',1),
('Henrique Lima','1E','henrique.lima552@aluno.educacao.sp.gov.br',1),
('Sofia Carvalho','3D','sofia.carvalho553@aluno.educacao.sp.gov.br',1),
('Emanuel Gomes','3A','emanuel.gomes554@aluno.educacao.sp.gov.br',1),
('Marcos Barbosa','2G','marcos.barbosa555@aluno.educacao.sp.gov.br',1),
('Nina Azevedo','2E','nina.azevedo556@aluno.educacao.sp.gov.br',1),
('Bruna Braga','2A','bruna.braga557@aluno.educacao.sp.gov.br',1),
('Bianca Rocha Nunes','3C','bianca.rocha.nunes558@aluno.educacao.sp.gov.br',1),
('Ana Araújo','3A','ana.araujo559@aluno.educacao.sp.gov.br',1),
('Vitor Rocha','3E','vitor.rocha560@aluno.educacao.sp.gov.br',1),
('Thiago Duarte','1C','thiago.duarte561@aluno.educacao.sp.gov.br',1),
('Laura Lopes','2C','laura.lopes562@aluno.educacao.sp.gov.br',1),
('Vitor Freitas','3D','vitor.freitas563@aluno.educacao.sp.gov.br',1),
('Sofia Pereira','1E','sofia.pereira564@aluno.educacao.sp.gov.br',1),
('Diego Moura Moreira','2C','diego.moura.moreira565@aluno.educacao.sp.gov.br',1),
('André Martins','2G','andre.martins566@aluno.educacao.sp.gov.br',1),
('Ruan Santos Mendes','3B','ruan.santos.mendes567@aluno.educacao.sp.gov.br',1),
('Camila Santana','2A','camila.santana568@aluno.educacao.sp.gov.br',1),
('Alexandre Mota','3F','alexandre.mota569@aluno.educacao.sp.gov.br',1),
('Eduardo Ribeiro','2F','eduardo.ribeiro570@aluno.educacao.sp.gov.br',1),
('Henrique Barbosa','3G','henrique.barbosa571@aluno.educacao.sp.gov.br',1),
('Lucas Freitas','2D','lucas.freitas572@aluno.educacao.sp.gov.br',1),
('Matheus Moura','1A','matheus.moura573@aluno.educacao.sp.gov.br',1),
('Samuel Lopes Nunes','2E','samuel.lopes.nunes574@aluno.educacao.sp.gov.br',1),
('Isabela Rocha','1D','isabela.rocha575@aluno.educacao.sp.gov.br',1),
('Isabela Pinto','2D','isabela.pinto576@aluno.educacao.sp.gov.br',1),
('Fernando Pires','3E','fernando.pires577@aluno.educacao.sp.gov.br',1),
('Caio Pires Campos','3C','caio.pires.campos578@aluno.educacao.sp.gov.br',1),
('Bruno Pinto','2D','bruno.pinto579@aluno.educacao.sp.gov.br',1),
('Diego Campos','2G','diego.campos580@aluno.educacao.sp.gov.br',1),
('Fabiana Moreira','2E','fabiana.moreira581@aluno.educacao.sp.gov.br',1),
('Vitor Oliveira','3F','vitor.oliveira582@aluno.educacao.sp.gov.br',1),
('Gabriel Azevedo','3D','gabriel.azevedo583@aluno.educacao.sp.gov.br',1),
('Maria Costa','2A','maria.costa584@aluno.educacao.sp.gov.br',1),
('Fernando Oliveira Braga','1B','fernando.oliveira.braga585@aluno.educacao.sp.gov.br',1),
('Igor Almeida Fernandes','3D','igor.almeida.fernandes586@aluno.educacao.sp.gov.br',1),
('Júlia Rocha','3C','julia.rocha587@aluno.educacao.sp.gov.br',1),
('Bruna Araújo','3D','bruna.araujo588@aluno.educacao.sp.gov.br',1),
('Marcos Moura','3A','marcos.moura589@aluno.educacao.sp.gov.br',1),
('Clara Martins','3A','clara.martins590@aluno.educacao.sp.gov.br',1),
('André Azevedo Campos','1E','andre.azevedo.campos591@aluno.educacao.sp.gov.br',1),
('Gustavo Branco Fernandes','1F','gustavo.branco.fernandes592@aluno.educacao.sp.gov.br',1),
('Cecília Teixeira','1E','cecilia.teixeira593@aluno.educacao.sp.gov.br',1),
('Matheus Nogueira Ferreira','1C','matheus.nogueira.ferreira594@aluno.educacao.sp.gov.br',1),
('Luan Almeida Moura','2F','luan.almeida.moura595@aluno.educacao.sp.gov.br',1),
('Eduardo Nogueira','1C','eduardo.nogueira596@aluno.educacao.sp.gov.br',1),
('Amanda Araújo','2C','amanda.araujo597@aluno.educacao.sp.gov.br',1),
('Caio Fernandes','1B','caio.fernandes598@aluno.educacao.sp.gov.br',1),
('Marcos Barbosa','3G','marcos.barbosa599@aluno.educacao.sp.gov.br',1),
('Gabriel Nunes','3A','gabriel.nunes600@aluno.educacao.sp.gov.br',1);

INSERT INTO alunos (nome, serie, email, professor_id) VALUES
('Ricardo Pires','3C','ricardo.pires601@aluno.educacao.sp.gov.br',1),
('Marcos Santana','1C','marcos.santana602@aluno.educacao.sp.gov.br',1),
('Igor Silva Pereira','1G','igor.silva.pereira603@aluno.educacao.sp.gov.br',1),
('Gustavo Araújo','1D','gustavo.araujo604@aluno.educacao.sp.gov.br',1),
('Nicolas Fernandes Pinto','2E','nicolas.fernandes.pinto605@aluno.educacao.sp.gov.br',1),
('Sérgio Azevedo','3C','sergio.azevedo606@aluno.educacao.sp.gov.br',1),
('Marcos Costa','3E','marcos.costa607@aluno.educacao.sp.gov.br',1),
('Fabiana Santana','1D','fabiana.santana608@aluno.educacao.sp.gov.br',1),
('Nicole Costa Viana','3F','nicole.costa.viana609@aluno.educacao.sp.gov.br',1),
('Larissa Cardoso Silva','3A','larissa.cardoso.silva610@aluno.educacao.sp.gov.br',1),
('Paulo Nunes','1E','paulo.nunes611@aluno.educacao.sp.gov.br',1),
('Alexandre Teixeira','1G','alexandre.teixeira612@aluno.educacao.sp.gov.br',1),
('Bruno Mota','1G','bruno.mota613@aluno.educacao.sp.gov.br',1),
('Felipe Freitas','3A','felipe.freitas614@aluno.educacao.sp.gov.br',1),
('Isabela Costa Araújo','2F','isabela.costa.araujo615@aluno.educacao.sp.gov.br',1),
('Renata Nunes Viana','1C','renata.nunes.viana616@aluno.educacao.sp.gov.br',1),
('Beatriz Martins','2G','beatriz.martins617@aluno.educacao.sp.gov.br',1),
('Larissa Rocha','3E','larissa.rocha618@aluno.educacao.sp.gov.br',1),
('Matheus Azevedo Ferreira','1B','matheus.azevedo.ferreira619@aluno.educacao.sp.gov.br',1),
('Felipe Correia','2B','felipe.correia620@aluno.educacao.sp.gov.br',1),
('Caio Silva','2G','caio.silva621@aluno.educacao.sp.gov.br',1),
('Vitor Teixeira','2C','vitor.teixeira622@aluno.educacao.sp.gov.br',1),
('Carolina Souza Pereira','3D','carolina.souza.pereira623@aluno.educacao.sp.gov.br',1),
('Emanuel Rocha','1E','emanuel.rocha624@aluno.educacao.sp.gov.br',1),
('Henrique Mota','3B','henrique.mota625@aluno.educacao.sp.gov.br',1),
('Ivo Silva','1G','ivo.silva626@aluno.educacao.sp.gov.br',1),
('Daniela Costa','1B','daniela.costa627@aluno.educacao.sp.gov.br',1),
('Beatriz Pereira Rocha','3D','beatriz.pereira.rocha628@aluno.educacao.sp.gov.br',1),
('Camila Faria','2D','camila.faria629@aluno.educacao.sp.gov.br',1),
('Isabela Pereira','2G','isabela.pereira630@aluno.educacao.sp.gov.br',1),
('Igor Faria','2G','igor.faria631@aluno.educacao.sp.gov.br',1),
('Patrícia Santana','2F','patricia.santana632@aluno.educacao.sp.gov.br',1),
('Guilherme Silva','2A','guilherme.silva633@aluno.educacao.sp.gov.br',1),
('Ana Santana','1G','ana.santana634@aluno.educacao.sp.gov.br',1),
('Júlia Lima','2E','julia.lima635@aluno.educacao.sp.gov.br',1),
('Pedro Rocha','3B','pedro.rocha636@aluno.educacao.sp.gov.br',1),
('Pedro Nunes Moreira','3G','pedro.nunes.moreira637@aluno.educacao.sp.gov.br',1),
('Thiago Mota','2F','thiago.mota638@aluno.educacao.sp.gov.br',1),
('Luan Rocha','1E','luan.rocha639@aluno.educacao.sp.gov.br',1),
('Bruna Faria','3D','bruna.faria640@aluno.educacao.sp.gov.br',1),
('Igor Souza','3B','igor.souza641@aluno.educacao.sp.gov.br',1),
('Amanda Souza','1F','amanda.souza642@aluno.educacao.sp.gov.br',1),
('Patrícia Silva','1E','patricia.silva643@aluno.educacao.sp.gov.br',1),
('Vânia Correia','1G','vania.correia644@aluno.educacao.sp.gov.br',1),
('Marcos Correia','1C','marcos.correia645@aluno.educacao.sp.gov.br',1),
('Patrícia Azevedo Martins','2F','patricia.azevedo.martins646@aluno.educacao.sp.gov.br',1),
('Isabela Nogueira','2F','isabela.nogueira647@aluno.educacao.sp.gov.br',1),
('Caio Oliveira Castro','3D','caio.oliveira.castro648@aluno.educacao.sp.gov.br',1),
('Beatriz Castro','1B','beatriz.castro649@aluno.educacao.sp.gov.br',1),
('Eduardo Martins','3E','eduardo.martins650@aluno.educacao.sp.gov.br',1),
('Diego Duarte','2C','diego.duarte651@aluno.educacao.sp.gov.br',1),
('João Moreira','2G','joao.moreira652@aluno.educacao.sp.gov.br',1),
('Isabela Azevedo','2A','isabela.azevedo653@aluno.educacao.sp.gov.br',1),
('Marcos Alves Nogueira','2A','marcos.alves.nogueira654@aluno.educacao.sp.gov.br',1),
('Guilherme Fernandes','3C','guilherme.fernandes655@aluno.educacao.sp.gov.br',1),
('Renata Silva','2A','renata.silva656@aluno.educacao.sp.gov.br',1),
('Isabela Azevedo','2C','isabela.azevedo657@aluno.educacao.sp.gov.br',1),
('Patrícia Pires','3D','patricia.pires658@aluno.educacao.sp.gov.br',1),
('Gabriel Duarte','1F','gabriel.duarte659@aluno.educacao.sp.gov.br',1),
('Henrique Faria','2E','henrique.faria660@aluno.educacao.sp.gov.br',1),
('Thiago Viana','3A','thiago.viana661@aluno.educacao.sp.gov.br',1),
('Ruan Mendes','1C','ruan.mendes662@aluno.educacao.sp.gov.br',1),
('Ruan Oliveira','3G','ruan.oliveira663@aluno.educacao.sp.gov.br',1),
('Guilherme Mendes Fernandes','3D','guilherme.mendes.fernandes664@aluno.educacao.sp.gov.br',1),
('Murilo Lima','3B','murilo.lima665@aluno.educacao.sp.gov.br',1),
('Luan Alves Costa','3F','luan.alves.costa666@aluno.educacao.sp.gov.br',1),
('Murilo Lima','3B','murilo.lima667@aluno.educacao.sp.gov.br',1),
('Matheus Freitas','2G','matheus.freitas668@aluno.educacao.sp.gov.br',1),
('Guilherme Martins','1G','guilherme.martins669@aluno.educacao.sp.gov.br',1),
('Bruno Silva Souza','1C','bruno.silva.souza670@aluno.educacao.sp.gov.br',1),
('Lívia Pinto','3D','livia.pinto671@aluno.educacao.sp.gov.br',1),
('Helena Nogueira','1B','helena.nogueira672@aluno.educacao.sp.gov.br',1),
('Olívia Pinto','3F','olivia.pinto673@aluno.educacao.sp.gov.br',1),
('Laura Duarte','3D','laura.duarte674@aluno.educacao.sp.gov.br',1),
('Ivo Souza','3C','ivo.souza675@aluno.educacao.sp.gov.br',1),
('Júlia Melo','3D','julia.melo676@aluno.educacao.sp.gov.br',1),
('Ivo Correia','2F','ivo.correia677@aluno.educacao.sp.gov.br',1),
('Rafael Moura','2D','rafael.moura678@aluno.educacao.sp.gov.br',1),
('Alexandre Correia Pinto','3D','alexandre.correia.pinto679@aluno.educacao.sp.gov.br',1),
('Ricardo Moura','1A','ricardo.moura680@aluno.educacao.sp.gov.br',1),
('Mariana Faria','3E','mariana.faria681@aluno.educacao.sp.gov.br',1),
('Gustavo Silva','2C','gustavo.silva682@aluno.educacao.sp.gov.br',1),
('Samuel Viana','1B','samuel.viana683@aluno.educacao.sp.gov.br',1),
('Bruno Braga','2D','bruno.braga684@aluno.educacao.sp.gov.br',1),
('Sérgio Mota Araújo','3E','sergio.mota.araujo685@aluno.educacao.sp.gov.br',1),
('Beatriz Oliveira Souza','2D','beatriz.oliveira.souza686@aluno.educacao.sp.gov.br',1),
('Samuel Viana','1F','samuel.viana687@aluno.educacao.sp.gov.br',1),
('Nicole Correia','1E','nicole.correia688@aluno.educacao.sp.gov.br',1),
('Otávio Braga','3F','otavio.braga689@aluno.educacao.sp.gov.br',1),
('Pedro Pinto','3C','pedro.pinto690@aluno.educacao.sp.gov.br',1),
('Nicole Silva','2B','nicole.silva691@aluno.educacao.sp.gov.br',1),
('Cecília Lopes','2C','cecilia.lopes692@aluno.educacao.sp.gov.br',1),
('Bruno Santos','1B','bruno.santos693@aluno.educacao.sp.gov.br',1),
('Luan Carvalho','2A','luan.carvalho694@aluno.educacao.sp.gov.br',1),
('Emanuel Santana','1D','emanuel.santana695@aluno.educacao.sp.gov.br',1),
('Rafael Teixeira','2F','rafael.teixeira696@aluno.educacao.sp.gov.br',1),
('Samuel Santana Duarte','1A','samuel.santana.duarte697@aluno.educacao.sp.gov.br',1),
('Carolina Nogueira','3G','carolina.nogueira698@aluno.educacao.sp.gov.br',1),
('Eduardo Ribeiro','1G','eduardo.ribeiro699@aluno.educacao.sp.gov.br',1),
('Samuel Santana','3F','samuel.santana700@aluno.educacao.sp.gov.br',1),
('Nicole Correia','1G','nicole.correia701@aluno.educacao.sp.gov.br',1),
('Patrícia Azevedo','1B','patricia.azevedo702@aluno.educacao.sp.gov.br',1),
('Renata Melo Gomes','3G','renata.melo.gomes703@aluno.educacao.sp.gov.br',1),
('Amanda Barbosa','2B','amanda.barbosa704@aluno.educacao.sp.gov.br',1),
('Pedro Cardoso','1B','pedro.cardoso705@aluno.educacao.sp.gov.br',1),
('Bruna Gomes','3B','bruna.gomes706@aluno.educacao.sp.gov.br',1),
('Beatriz Santos','3D','beatriz.santos707@aluno.educacao.sp.gov.br',1),
('Nina Nunes Duarte','2G','nina.nunes.duarte708@aluno.educacao.sp.gov.br',1),
('Mariana Moura','3E','mariana.moura709@aluno.educacao.sp.gov.br',1),
('Rafael Braga','3A','rafael.braga710@aluno.educacao.sp.gov.br',1),
('Diego Duarte','3D','diego.duarte711@aluno.educacao.sp.gov.br',1),
('Igor Moreira Araújo','1A','igor.moreira.araujo712@aluno.educacao.sp.gov.br',1),
('Nicolas Pinto','3G','nicolas.pinto713@aluno.educacao.sp.gov.br',1),
('André Mota','1E','andre.mota714@aluno.educacao.sp.gov.br',1),
('Ruan Branco Azevedo','3B','ruan.branco.azevedo715@aluno.educacao.sp.gov.br',1),
('Cecília Almeida Silva','1F','cecilia.almeida.silva716@aluno.educacao.sp.gov.br',1),
('Caio Almeida','2B','caio.almeida717@aluno.educacao.sp.gov.br',1),
('Luan Castro Viana','3A','luan.castro.viana718@aluno.educacao.sp.gov.br',1),
('Alexandre Nunes','1A','alexandre.nunes719@aluno.educacao.sp.gov.br',1),
('Clara Carvalho Nunes','2G','clara.carvalho.nunes720@aluno.educacao.sp.gov.br',1),
('Ivo Lima','1C','ivo.lima721@aluno.educacao.sp.gov.br',1),
('Sérgio Mendes','2A','sergio.mendes722@aluno.educacao.sp.gov.br',1),
('Ricardo Freitas','3G','ricardo.freitas723@aluno.educacao.sp.gov.br',1),
('Cecília Rocha','2B','cecilia.rocha724@aluno.educacao.sp.gov.br',1),
('Carolina Faria','2D','carolina.faria725@aluno.educacao.sp.gov.br',1),
('Vânia Viana','1C','vania.viana726@aluno.educacao.sp.gov.br',1),
('Bruno Correia','1C','bruno.correia727@aluno.educacao.sp.gov.br',1),
('Júlia Alves Moura','3C','julia.alves.moura728@aluno.educacao.sp.gov.br',1),
('Sérgio Castro','1D','sergio.castro729@aluno.educacao.sp.gov.br',1),
('Henrique Almeida','2G','henrique.almeida730@aluno.educacao.sp.gov.br',1),
('Otávio Mota','3G','otavio.mota731@aluno.educacao.sp.gov.br',1),
('Emanuel Alves Pereira','1G','emanuel.alves.pereira732@aluno.educacao.sp.gov.br',1),
('Thiago Araújo','3D','thiago.araujo733@aluno.educacao.sp.gov.br',1),
('Rafael Barbosa Faria','2D','rafael.barbosa.faria734@aluno.educacao.sp.gov.br',1),
('Laura Lima Mota','2F','laura.lima.mota735@aluno.educacao.sp.gov.br',1),
('Otávio Ribeiro','3C','otavio.ribeiro736@aluno.educacao.sp.gov.br',1),
('Fernando Almeida','2A','fernando.almeida737@aluno.educacao.sp.gov.br',1),
('Laura Araújo','3B','laura.araujo738@aluno.educacao.sp.gov.br',1),
('Ruan Carvalho','3C','ruan.carvalho739@aluno.educacao.sp.gov.br',1),
('Lucas Azevedo','2A','lucas.azevedo740@aluno.educacao.sp.gov.br',1),
('Laura Pires','1D','laura.pires741@aluno.educacao.sp.gov.br',1),
('Fernando Correia','1G','fernando.correia742@aluno.educacao.sp.gov.br',1),
('Clara Ribeiro','3B','clara.ribeiro743@aluno.educacao.sp.gov.br',1),
('Bruno Freitas Nunes','3C','bruno.freitas.nunes744@aluno.educacao.sp.gov.br',1),
('Emanuel Braga','2G','emanuel.braga745@aluno.educacao.sp.gov.br',1),
('Nicolas Carvalho','1F','nicolas.carvalho746@aluno.educacao.sp.gov.br',1),
('Pedro Silva','3A','pedro.silva747@aluno.educacao.sp.gov.br',1),
('Igor Campos','2D','igor.campos748@aluno.educacao.sp.gov.br',1),
('Diego Silva','3G','diego.silva749@aluno.educacao.sp.gov.br',1),
('Murilo Souza','1F','murilo.souza750@aluno.educacao.sp.gov.br',1),
('Helena Barbosa','3E','helena.barbosa751@aluno.educacao.sp.gov.br',1),
('Gustavo Castro','3B','gustavo.castro752@aluno.educacao.sp.gov.br',1),
('Luan Lopes','3D','luan.lopes753@aluno.educacao.sp.gov.br',1),
('Vitor Oliveira','2A','vitor.oliveira754@aluno.educacao.sp.gov.br',1),
('Carolina Lopes Mota','2C','carolina.lopes.mota755@aluno.educacao.sp.gov.br',1),
('Henrique Azevedo Costa','1G','henrique.azevedo.costa756@aluno.educacao.sp.gov.br',1),
('Gustavo Araújo','3F','gustavo.araujo757@aluno.educacao.sp.gov.br',1),
('Lívia Nogueira Cardoso','3A','livia.nogueira.cardoso758@aluno.educacao.sp.gov.br',1),
('Lucas Souza','1E','lucas.souza759@aluno.educacao.sp.gov.br',1),
('Lucas Carvalho','3F','lucas.carvalho760@aluno.educacao.sp.gov.br',1),
('Guilherme Lima','1A','guilherme.lima761@aluno.educacao.sp.gov.br',1),
('Daniela Souza','2E','daniela.souza762@aluno.educacao.sp.gov.br',1),
('Patrícia Costa','1G','patricia.costa763@aluno.educacao.sp.gov.br',1),
('Guilherme Faria','3B','guilherme.faria764@aluno.educacao.sp.gov.br',1),
('Ricardo Alves','1F','ricardo.alves765@aluno.educacao.sp.gov.br',1),
('Bruna Melo','2F','bruna.melo766@aluno.educacao.sp.gov.br',1),
('Isabela Campos','2C','isabela.campos767@aluno.educacao.sp.gov.br',1),
('Otávio Araújo','2A','otavio.araujo768@aluno.educacao.sp.gov.br',1),
('Eduardo Azevedo','3D','eduardo.azevedo769@aluno.educacao.sp.gov.br',1),
('Fabiana Santos','2C','fabiana.santos770@aluno.educacao.sp.gov.br',1),
('Nicolas Alves','1C','nicolas.alves771@aluno.educacao.sp.gov.br',1),
('Ana Cardoso Nogueira','2C','ana.cardoso.nogueira772@aluno.educacao.sp.gov.br',1),
('Maria Martins','1E','maria.martins773@aluno.educacao.sp.gov.br',1),
('Fabiana Alves Nunes','1E','fabiana.alves.nunes774@aluno.educacao.sp.gov.br',1),
('Mariana Faria','3B','mariana.faria775@aluno.educacao.sp.gov.br',1),
('Nicolas Nogueira','2E','nicolas.nogueira776@aluno.educacao.sp.gov.br',1),
('Alexandre Lopes','1F','alexandre.lopes777@aluno.educacao.sp.gov.br',1),
('Murilo Braga','1E','murilo.braga778@aluno.educacao.sp.gov.br',1),
('Vitória Oliveira','1A','vitoria.oliveira779@aluno.educacao.sp.gov.br',1),
('Lucas Pereira','1F','lucas.pereira780@aluno.educacao.sp.gov.br',1),
('Samuel Faria Campos','2B','samuel.faria.campos781@aluno.educacao.sp.gov.br',1),
('Larissa Lopes','1B','larissa.lopes782@aluno.educacao.sp.gov.br',1),
('Gustavo Azevedo','2F','gustavo.azevedo783@aluno.educacao.sp.gov.br',1),
('Eduardo Santos','3D','eduardo.santos784@aluno.educacao.sp.gov.br',1),
('Patrícia Moura','3C','patricia.moura785@aluno.educacao.sp.gov.br',1),
('Nina Faria','1B','nina.faria786@aluno.educacao.sp.gov.br',1),
('Maria Carvalho','3F','maria.carvalho787@aluno.educacao.sp.gov.br',1),
('Samuel Silva','1G','samuel.silva788@aluno.educacao.sp.gov.br',1),
('Helena Araújo','3F','helena.araujo789@aluno.educacao.sp.gov.br',1),
('Patrícia Ribeiro','3A','patricia.ribeiro790@aluno.educacao.sp.gov.br',1),
('Júlia Pereira','3E','julia.pereira791@aluno.educacao.sp.gov.br',1),
('Caio Branco','3E','caio.branco792@aluno.educacao.sp.gov.br',1),
('Nicolas Almeida','1D','nicolas.almeida793@aluno.educacao.sp.gov.br',1),
('Ruan Nogueira','3B','ruan.nogueira794@aluno.educacao.sp.gov.br',1),
('Fabiana Gomes','2E','fabiana.gomes795@aluno.educacao.sp.gov.br',1),
('Fabiana Cardoso','3C','fabiana.cardoso796@aluno.educacao.sp.gov.br',1),
('Luan Azevedo','1F','luan.azevedo797@aluno.educacao.sp.gov.br',1),
('Lívia Martins','2B','livia.martins798@aluno.educacao.sp.gov.br',1),
('André Pereira','3B','andre.pereira799@aluno.educacao.sp.gov.br',1),
('Diego Alves','1A','diego.alves800@aluno.educacao.sp.gov.br',1);

INSERT INTO alunos (nome, serie, email, professor_id) VALUES
('Renata Barbosa','3C','renata.barbosa801@aluno.educacao.sp.gov.br',1),
('Cecília Correia','2A','cecilia.correia802@aluno.educacao.sp.gov.br',1),
('Fabiana Pinto','3D','fabiana.pinto803@aluno.educacao.sp.gov.br',1),
('Bruna Nogueira','3G','bruna.nogueira804@aluno.educacao.sp.gov.br',1),
('Marcos Almeida','2A','marcos.almeida805@aluno.educacao.sp.gov.br',1),
('Lucas Rocha','1G','lucas.rocha806@aluno.educacao.sp.gov.br',1),
('Pedro Pereira Ferreira','2E','pedro.pereira.ferreira807@aluno.educacao.sp.gov.br',1),
('João Santana','1E','joao.santana808@aluno.educacao.sp.gov.br',1),
('Samuel Lopes','3A','samuel.lopes809@aluno.educacao.sp.gov.br',1),
('Gabriel Cardoso','2G','gabriel.cardoso810@aluno.educacao.sp.gov.br',1),
('Bianca Silva','2E','bianca.silva811@aluno.educacao.sp.gov.br',1),
('Renata Rocha Pereira','2F','renata.rocha.pereira812@aluno.educacao.sp.gov.br',1),
('Fabiana Castro','1D','fabiana.castro813@aluno.educacao.sp.gov.br',1),
('Paulo Melo','2A','paulo.melo814@aluno.educacao.sp.gov.br',1),
('Nicolas Melo','1E','nicolas.melo815@aluno.educacao.sp.gov.br',1),
('Vitória Viana','2B','vitoria.viana816@aluno.educacao.sp.gov.br',1),
('Vitor Branco','2C','vitor.branco817@aluno.educacao.sp.gov.br',1),
('Lorena Duarte','3G','lorena.duarte818@aluno.educacao.sp.gov.br',1),
('Lívia Santos','2D','livia.santos819@aluno.educacao.sp.gov.br',1),
('Patrícia Moura Freitas','1B','patricia.moura.freitas820@aluno.educacao.sp.gov.br',1),
('Fabiana Braga','2F','fabiana.braga821@aluno.educacao.sp.gov.br',1),
('Bruna Costa','2G','bruna.costa822@aluno.educacao.sp.gov.br',1),
('Nicolas Silva','1G','nicolas.silva823@aluno.educacao.sp.gov.br',1),
('Beatriz Martins Pinto','2G','beatriz.martins.pinto824@aluno.educacao.sp.gov.br',1),
('Camila Costa','1B','camila.costa825@aluno.educacao.sp.gov.br',1),
('Laura Santos Araújo','3B','laura.santos.araujo826@aluno.educacao.sp.gov.br',1),
('Helena Moura','1B','helena.moura827@aluno.educacao.sp.gov.br',1),
('Bruno Gomes','2D','bruno.gomes828@aluno.educacao.sp.gov.br',1),
('Ricardo Fernandes','3D','ricardo.fernandes829@aluno.educacao.sp.gov.br',1),
('Felipe Melo','3F','felipe.melo830@aluno.educacao.sp.gov.br',1),
('Lorena Campos','2D','lorena.campos831@aluno.educacao.sp.gov.br',1),
('João Araújo','3F','joao.araujo832@aluno.educacao.sp.gov.br',1),
('Cecília Nunes','2A','cecilia.nunes833@aluno.educacao.sp.gov.br',1),
('Ana Duarte','1F','ana.duarte834@aluno.educacao.sp.gov.br',1),
('Rafael Ribeiro','3A','rafael.ribeiro835@aluno.educacao.sp.gov.br',1),
('Helena Campos Almeida','1C','helena.campos.almeida836@aluno.educacao.sp.gov.br',1),
('Nicole Santos','3A','nicole.santos837@aluno.educacao.sp.gov.br',1),
('Clara Pinto','3E','clara.pinto838@aluno.educacao.sp.gov.br',1),
('Gabriel Campos','2G','gabriel.campos839@aluno.educacao.sp.gov.br',1),
('Henrique Duarte','3B','henrique.duarte840@aluno.educacao.sp.gov.br',1),
('Isabela Teixeira','2D','isabela.teixeira841@aluno.educacao.sp.gov.br',1),
('Sofia Oliveira Mendes','2B','sofia.oliveira.mendes842@aluno.educacao.sp.gov.br',1),
('Ruan Lima','1B','ruan.lima843@aluno.educacao.sp.gov.br',1),
('Otávio Campos Correia','2F','otavio.campos.correia844@aluno.educacao.sp.gov.br',1),
('Fabiana Rocha','3C','fabiana.rocha845@aluno.educacao.sp.gov.br',1),
('Fabiana Santana Duarte','1B','fabiana.santana.duarte846@aluno.educacao.sp.gov.br',1),
('Camila Pinto','1D','camila.pinto847@aluno.educacao.sp.gov.br',1),
('Laura Almeida','2C','laura.almeida848@aluno.educacao.sp.gov.br',1),
('Sérgio Gomes','3A','sergio.gomes849@aluno.educacao.sp.gov.br',1),
('Samuel Costa Branco','2E','samuel.costa.branco850@aluno.educacao.sp.gov.br',1),
('Diego Ferreira','2B','diego.ferreira851@aluno.educacao.sp.gov.br',1),
('Rafael Lopes','1E','rafael.lopes852@aluno.educacao.sp.gov.br',1),
('Samuel Viana Gomes','2A','samuel.viana.gomes853@aluno.educacao.sp.gov.br',1),
('Bianca Gomes','1D','bianca.gomes854@aluno.educacao.sp.gov.br',1),
('Cecília Pereira','1G','cecilia.pereira855@aluno.educacao.sp.gov.br',1),
('Carolina Freitas','1B','carolina.freitas856@aluno.educacao.sp.gov.br',1),
('Nicolas Lima','1D','nicolas.lima857@aluno.educacao.sp.gov.br',1),
('Pedro Nogueira','1G','pedro.nogueira858@aluno.educacao.sp.gov.br',1),
('Júlia Santana','2F','julia.santana859@aluno.educacao.sp.gov.br',1),
('Fabiana Santana','1C','fabiana.santana860@aluno.educacao.sp.gov.br',1),
('Pedro Rocha Costa','2A','pedro.rocha.costa861@aluno.educacao.sp.gov.br',1),
('Laura Fernandes Teixeira','1E','laura.fernandes.teixeira862@aluno.educacao.sp.gov.br',1),
('Matheus Branco','1G','matheus.branco863@aluno.educacao.sp.gov.br',1),
('Eduardo Branco','3E','eduardo.branco864@aluno.educacao.sp.gov.br',1),
('Laura Viana','1G','laura.viana865@aluno.educacao.sp.gov.br',1),
('Helena Martins','2E','helena.martins866@aluno.educacao.sp.gov.br',1),
('Guilherme Lima','3D','guilherme.lima867@aluno.educacao.sp.gov.br',1),
('Fabiana Ferreira','1G','fabiana.ferreira868@aluno.educacao.sp.gov.br',1),
('Maria Almeida','3A','maria.almeida869@aluno.educacao.sp.gov.br',1),
('Gabriel Alves','3D','gabriel.alves870@aluno.educacao.sp.gov.br',1),
('Patrícia Azevedo','2F','patricia.azevedo871@aluno.educacao.sp.gov.br',1),
('Henrique Santana Souza','1C','henrique.santana.souza872@aluno.educacao.sp.gov.br',1),
('Mariana Teixeira','3A','mariana.teixeira873@aluno.educacao.sp.gov.br',1),
('Nina Barbosa','3C','nina.barbosa874@aluno.educacao.sp.gov.br',1),
('Pedro Moura','2F','pedro.moura875@aluno.educacao.sp.gov.br',1),
('Daniela Moreira Pereira','1G','daniela.moreira.pereira876@aluno.educacao.sp.gov.br',1),
('Ana Melo','2C','ana.melo877@aluno.educacao.sp.gov.br',1),
('Isabela Araújo','3F','isabela.araujo878@aluno.educacao.sp.gov.br',1),
('Otávio Azevedo','3B','otavio.azevedo879@aluno.educacao.sp.gov.br',1),
('Sofia Martins','1A','sofia.martins880@aluno.educacao.sp.gov.br',1),
('Carolina Martins Faria','2G','carolina.martins.faria881@aluno.educacao.sp.gov.br',1),
('Guilherme Pinto Freitas','2A','guilherme.pinto.freitas882@aluno.educacao.sp.gov.br',1),
('Samuel Almeida Carvalho','1F','samuel.almeida.carvalho883@aluno.educacao.sp.gov.br',1),
('Rafael Carvalho','1C','rafael.carvalho884@aluno.educacao.sp.gov.br',1),
('Bruna Cardoso','1A','bruna.cardoso885@aluno.educacao.sp.gov.br',1),
('André Lima','1D','andre.lima886@aluno.educacao.sp.gov.br',1),
('Sofia Campos','2A','sofia.campos887@aluno.educacao.sp.gov.br',1),
('Murilo Moura','1A','murilo.moura888@aluno.educacao.sp.gov.br',1),
('Nina Moreira','1A','nina.moreira889@aluno.educacao.sp.gov.br',1),
('Amanda Cardoso','2F','amanda.cardoso890@aluno.educacao.sp.gov.br',1),
('Mariana Faria','3E','mariana.faria891@aluno.educacao.sp.gov.br',1),
('Eduardo Martins Araújo','1C','eduardo.martins.araujo892@aluno.educacao.sp.gov.br',1),
('Luan Rocha','1C','luan.rocha893@aluno.educacao.sp.gov.br',1),
('Thiago Nogueira Faria','3G','thiago.nogueira.faria894@aluno.educacao.sp.gov.br',1),
('Guilherme Santos','1C','guilherme.santos895@aluno.educacao.sp.gov.br',1),
('Vitória Faria','3D','vitoria.faria896@aluno.educacao.sp.gov.br',1),
('Felipe Araújo','2F','felipe.araujo897@aluno.educacao.sp.gov.br',1),
('Murilo Gomes','3F','murilo.gomes898@aluno.educacao.sp.gov.br',1),
('Cecília Pires','1B','cecilia.pires899@aluno.educacao.sp.gov.br',1),
('Bruno Barbosa','3F','bruno.barbosa900@aluno.educacao.sp.gov.br',1),
('André Santana','1C','andre.santana901@aluno.educacao.sp.gov.br',1),
('Bruna Santana','2E','bruna.santana902@aluno.educacao.sp.gov.br',1),
('Paulo Souza','1D','paulo.souza903@aluno.educacao.sp.gov.br',1),
('Ivo Carvalho','2G','ivo.carvalho904@aluno.educacao.sp.gov.br',1),
('Matheus Araújo','2E','matheus.araujo905@aluno.educacao.sp.gov.br',1),
('Laura Melo','1F','laura.melo906@aluno.educacao.sp.gov.br',1),
('Carolina Faria','1E','carolina.faria907@aluno.educacao.sp.gov.br',1),
('Matheus Ribeiro','1B','matheus.ribeiro908@aluno.educacao.sp.gov.br',1),
('Thiago Araújo','2C','thiago.araujo909@aluno.educacao.sp.gov.br',1),
('Clara Fernandes','2A','clara.fernandes910@aluno.educacao.sp.gov.br',1),
('Patrícia Pires Azevedo','1E','patricia.pires.azevedo911@aluno.educacao.sp.gov.br',1),
('Ricardo Oliveira','2D','ricardo.oliveira912@aluno.educacao.sp.gov.br',1),
('Emanuel Santos','3B','emanuel.santos913@aluno.educacao.sp.gov.br',1),
('Fabiana Mendes','3D','fabiana.mendes914@aluno.educacao.sp.gov.br',1),
('Helena Braga','1E','helena.braga915@aluno.educacao.sp.gov.br',1),
('Paulo Mota','3F','paulo.mota916@aluno.educacao.sp.gov.br',1),
('Bruno Costa','2A','bruno.costa917@aluno.educacao.sp.gov.br',1),
('Laura Pires','2B','laura.pires918@aluno.educacao.sp.gov.br',1),
('Bruno Nogueira Melo','2D','bruno.nogueira.melo919@aluno.educacao.sp.gov.br',1),
('Igor Souza','2G','igor.souza920@aluno.educacao.sp.gov.br',1),
('Caio Almeida','1G','caio.almeida921@aluno.educacao.sp.gov.br',1),
('Vitória Oliveira Ferreira','3A','vitoria.oliveira.ferreira922@aluno.educacao.sp.gov.br',1),
('Laura Almeida','1F','laura.almeida923@aluno.educacao.sp.gov.br',1),
('Paulo Rocha Ribeiro','1A','paulo.rocha.ribeiro924@aluno.educacao.sp.gov.br',1),
('Luan Santana','2F','luan.santana925@aluno.educacao.sp.gov.br',1),
('Emanuel Costa','2E','emanuel.costa926@aluno.educacao.sp.gov.br',1),
('Laura Azevedo','2A','laura.azevedo927@aluno.educacao.sp.gov.br',1),
('Eduardo Araújo','1E','eduardo.araujo928@aluno.educacao.sp.gov.br',1),
('Nicole Moreira','2E','nicole.moreira929@aluno.educacao.sp.gov.br',1),
('Fernando Freitas Teixeira','1C','fernando.freitas.teixeira930@aluno.educacao.sp.gov.br',1),
('Vitor Melo','2F','vitor.melo931@aluno.educacao.sp.gov.br',1),
('Bruno Azevedo','2F','bruno.azevedo932@aluno.educacao.sp.gov.br',1),
('Caio Martins','1A','caio.martins933@aluno.educacao.sp.gov.br',1),
('Rafael Silva','1B','rafael.silva934@aluno.educacao.sp.gov.br',1),
('Sofia Melo','2F','sofia.melo935@aluno.educacao.sp.gov.br',1),
('Luan Teixeira','3C','luan.teixeira936@aluno.educacao.sp.gov.br',1),
('Henrique Freitas','3G','henrique.freitas937@aluno.educacao.sp.gov.br',1),
('Bruna Lima','3F','bruna.lima938@aluno.educacao.sp.gov.br',1),
('Vitor Braga','2E','vitor.braga939@aluno.educacao.sp.gov.br',1),
('Diego Silva','2B','diego.silva940@aluno.educacao.sp.gov.br',1),
('Thiago Castro Correia','2E','thiago.castro.correia941@aluno.educacao.sp.gov.br',1),
('Ana Nogueira','2C','ana.nogueira942@aluno.educacao.sp.gov.br',1),
('Gabriel Alves','3A','gabriel.alves943@aluno.educacao.sp.gov.br',1),
('Murilo Teixeira','3G','murilo.teixeira944@aluno.educacao.sp.gov.br',1),
('Ivo Pires Campos','3B','ivo.pires.campos945@aluno.educacao.sp.gov.br',1),
('Eduardo Nunes','1G','eduardo.nunes946@aluno.educacao.sp.gov.br',1),
('Renata Duarte','3D','renata.duarte947@aluno.educacao.sp.gov.br',1),
('Beatriz Nogueira Barbosa','1E','beatriz.nogueira.barbosa948@aluno.educacao.sp.gov.br',1),
('Caio Fernandes','1E','caio.fernandes949@aluno.educacao.sp.gov.br',1),
('Isabela Duarte','2D','isabela.duarte950@aluno.educacao.sp.gov.br',1),
('Ivo Oliveira','1A','ivo.oliveira951@aluno.educacao.sp.gov.br',1),
('Sofia Correia Rocha','3E','sofia.correia.rocha952@aluno.educacao.sp.gov.br',1),
('Luan Castro','2C','luan.castro953@aluno.educacao.sp.gov.br',1),
('Ricardo Mendes Freitas','1G','ricardo.mendes.freitas954@aluno.educacao.sp.gov.br',1),
('Olívia Faria','2C','olivia.faria955@aluno.educacao.sp.gov.br',1),
('Patrícia Nogueira','1A','patricia.nogueira956@aluno.educacao.sp.gov.br',1),
('Laura Moura','1G','laura.moura957@aluno.educacao.sp.gov.br',1),
('Rafael Duarte','2B','rafael.duarte958@aluno.educacao.sp.gov.br',1),
('Amanda Pereira','2C','amanda.pereira959@aluno.educacao.sp.gov.br',1),
('Ana Castro Carvalho','3A','ana.castro.carvalho960@aluno.educacao.sp.gov.br',1),
('Carolina Ribeiro','1E','carolina.ribeiro961@aluno.educacao.sp.gov.br',1),
('Bruno Carvalho','1D','bruno.carvalho962@aluno.educacao.sp.gov.br',1),
('Larissa Campos','1G','larissa.campos963@aluno.educacao.sp.gov.br',1),
('Gabriel Lima','3B','gabriel.lima964@aluno.educacao.sp.gov.br',1),
('André Santana Duarte','2B','andre.santana.duarte965@aluno.educacao.sp.gov.br',1),
('João Pereira','3B','joao.pereira966@aluno.educacao.sp.gov.br',1),
('Luan Martins Castro','1G','luan.martins.castro967@aluno.educacao.sp.gov.br',1),
('Bruna Barbosa','3D','bruna.barbosa968@aluno.educacao.sp.gov.br',1),
('Henrique Barbosa','3E','henrique.barbosa969@aluno.educacao.sp.gov.br',1),
('Cecília Teixeira','2G','cecilia.teixeira970@aluno.educacao.sp.gov.br',1),
('Beatriz Viana','1D','beatriz.viana971@aluno.educacao.sp.gov.br',1),
('Samuel Cardoso','1A','samuel.cardoso972@aluno.educacao.sp.gov.br',1),
('Vitor Ferreira','2C','vitor.ferreira973@aluno.educacao.sp.gov.br',1),
('Laura Braga Freitas','3G','laura.braga.freitas974@aluno.educacao.sp.gov.br',1),
('Otávio Moura','2E','otavio.moura975@aluno.educacao.sp.gov.br',1),
('Igor Mendes','3F','igor.mendes976@aluno.educacao.sp.gov.br',1),
('Vânia Duarte','2C','vania.duarte977@aluno.educacao.sp.gov.br',1),
('João Nogueira','2F','joao.nogueira978@aluno.educacao.sp.gov.br',1),
('Henrique Freitas Nogueira','2B','henrique.freitas.nogueira979@aluno.educacao.sp.gov.br',1),
('Ruan Melo','2F','ruan.melo980@aluno.educacao.sp.gov.br',1),
('Vitor Ferreira','1B','vitor.ferreira981@aluno.educacao.sp.gov.br',1),
('Ricardo Souza','1F','ricardo.souza982@aluno.educacao.sp.gov.br',1),
('Lívia Gomes','1C','livia.gomes983@aluno.educacao.sp.gov.br',1),
('Pedro Lopes Pereira','2A','pedro.lopes.pereira984@aluno.educacao.sp.gov.br',1),
('Vitória Rocha','1G','vitoria.rocha985@aluno.educacao.sp.gov.br',1),
('Vânia Lopes Lima','1B','vania.lopes.lima986@aluno.educacao.sp.gov.br',1),
('Alexandre Alves','1G','alexandre.alves987@aluno.educacao.sp.gov.br',1),
('Daniela Gomes','1D','daniela.gomes988@aluno.educacao.sp.gov.br',1),
('Nina Oliveira Ribeiro','1G','nina.oliveira.ribeiro989@aluno.educacao.sp.gov.br',1),
('Murilo Costa','2D','murilo.costa990@aluno.educacao.sp.gov.br',1),
('Murilo Alves','3A','murilo.alves991@aluno.educacao.sp.gov.br',1),
('Gustavo Teixeira','2E','gustavo.teixeira992@aluno.educacao.sp.gov.br',1),
('Diego Pereira','1F','diego.pereira993@aluno.educacao.sp.gov.br',1),
('Bruno Oliveira','1E','bruno.oliveira994@aluno.educacao.sp.gov.br',1),
('Nicole Ferreira','2E','nicole.ferreira995@aluno.educacao.sp.gov.br',1),
('Otávio Oliveira','2E','otavio.oliveira996@aluno.educacao.sp.gov.br',1),
('Murilo Martins','3D','murilo.martins997@aluno.educacao.sp.gov.br',1),
('Caio Rocha Costa','2C','caio.rocha.costa998@aluno.educacao.sp.gov.br',1),
('Nicole Azevedo','3B','nicole.azevedo999@aluno.educacao.sp.gov.br',1),
('Luan Araújo','3G','luan.araujo1000@aluno.educacao.sp.gov.br',1);

